version: "3.7"

services:
  nginx:
    image: nginx:1.17-alpine
    container_name: 'diagnostics-nginx'
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
      - yarn
    volumes:
      - ./services/nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ../:/app

  php-fpm:
    build:
      context: ./services/php-fpm
    container_name: 'diagnostics-php-fpm'
    working_dir: /app
    depends_on:
      - mysql
    volumes:
      - ../:/app

  mysql:
    image: mysql:5.7.29
    container_name: 'diagnostics-mysql'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - diagnostics-mysql-data:/var/lib/mysql

  yarn:
    build:
      context: ./services/yarn
      dockerfile: Dockerfile
    container_name: 'diagnostics-yarn'
    working_dir: /app
#    user: 'node'
    volumes:
      - ../:/app

volumes:
  diagnostics-mysql-data: {}
